name: coffe
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dash: 1.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  carousel_slider: ^4.2.1
  test: ^1.24.9

flutter:
  uses-material-design: true

  assets:
  - images/
  # example:
  fonts:
    - family: OswaldBold
      fonts:
        - asset: fonts/Oswald-Bold.ttf
          style: italic
          weight: 500
